### ISSUE TITLE
How to change maps provider?

### ISSUE THREAD

**Issue by cuteUtya** [m0nac0/flutter-maplibre-gl#109]
I tried to use myptv.com maps, but i doing something wrong...

My code: 

```dart
MaplibreMap(
      onMapCreated: (controller) {
        controller.addSource(
          "myptv",
          const VectorSourceProperties(
            tiles: [
              "https://api.myptv.com/maps/v1/vector-tiles/{z}/{x}/{y}?apiKey=MY_API_KEY"
            ],
            minzoom: 0,
            maxzoom: 17,
          ),
        );
      },
      initialCameraPosition: const CameraPosition(
        bearing: 0,
        target: LatLng(0, 0),
      ),
    );
```

**Comment by m0nac0** [comment]
Vector tiles contain the map data, ordered into different layers, but no info on how to render that data. For that you need a map style. This plugin's default style works with the demo maplibre tiles, but not with your tiles. That's because your vector tiles contain different types of  map data, ordered into different layers. So you need to supply a map style to tell the plugin how to render the data in your map tiles. Does that make sense?

I'm not familiar with myptv.com but their docs at https://developer.myptv.com/Documentation/Vector%20Maps%20API/Concepts/Styling.htm suggest that they actually have some default styles, which you should be able to just use with this plugin. Just put the URL of the style into `MaplibreMap.styleString`

**Comment by cuteUtya** [comment]
Yep, thank for answer
