### ISSUE TITLE
maplibre_gl_web is still pulling mapbox_gl_dart transitively

### ISSUE THREAD

**Issue by kuhnroyal** [m0nac0/flutter-maplibre-gl#36]
```
|-- maplibre_gl 0.14.0
|   |-- flutter...
|   |-- maplibre_gl_platform_interface...
|   '-- maplibre_gl_web...
|-- maplibre_gl_platform_interface 0.14.0
|   |-- flutter...
|   '-- meta...
|-- maplibre_gl_web 0.14.0
|   |-- flutter...
|   |-- flutter_web_plugins...
|   |-- image 3.0.8
|   |   |-- archive...
|   |   |-- meta...
|   |   '-- xml...
|   |-- mapbox_gl_dart 0.2.0-nullsafety.0
|   |   '-- js...
|   |-- maplibre_gl_platform_interface...
|   '-- meta...
```

**Comment by m0nac0** [comment]
Yes, because we use one of the first releases of maplibre-gl-js, which still uses the old Mapbox namespace, thus we can use mapbox-gl-dart. This does not mean that Mapbox libraries are used, because the actual mapbox-gl-js/maplibre-gl-js is not pulled in by mapbox-gl-dart. (see: https://github.com/andrea689/mapbox-gl-dart#using-this-package
> You must include Mapbox GL JS into your .html file to be able to use this package.

---

If we want to upgrade maplibre-gl-js though, we will have to fork mapbox-gl-dart to create a maplibre-gl-dart. I suspect that it initially might be enough to just swap the Mapbox namespace references for Maplibre, but I haven't had time, yet, to test this.

**Comment by kuhnroyal** [comment]
I see, so these are basically just the bindings.

**Comment by m0nac0** [comment]
Closing since this is not a bug/problem.
